apiVersion: v1
data:
    age.agekey: ENC[AES256_GCM,data:rvbWIMDIKYKDo60tCDOPQh+Sr3XyCOS4IR+KtKJsK8Yu4aqWWFrupwL9iPrdpVDponFe8zQTTd3s4xm7UQciELC+/YYlrMwIKYHxLMlL269o0wKOjb3xUx4WBfTC2BaQZh6zEagKZv+g7K/JKa6mqX7bUsoB/gEwANdVJgCAgeBNS58sYEwz7wZ+rZ+hU3Pyk1cmxsLG8EDVc//0JOyBpOYgLiYuR01E+ODJx1ugs/ERvgGHICmpwqXwmiWMFmPnRP2GFANaDG5iZsUNrMnlhsy6qjXNJEU2akKKkygm8+tsj+Af5+HN7b4jtsw1uEeFDTZuJWiZ8gEwIsBE,iv:S/W3WafhgoAqxP3AEIHQ7J2sHmik/ORYvmFIzChXRhg=,tag:zQ5nbhlQExQigfrhdjFQ9Q==,type:str]
kind: Secret
metadata:
    name: age-key-secret
    namespace: flux-system
sops:
    age:
        - recipient: age19kyyjnd32na99sn2d4ktqddykrmnghu6tk34fsy9l9duyu2g95ssypk7vy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWdGhxQU1GSzVkbGFKd1Qy
            MUhyaDVYanpha1hFTUlrc2Zhb1RxRWZHWm00CmpFUTRkZEUzMWNKMFdPZWZyRHFD
            c1h4Y2MxYkg1bzRCVVFJSEF1TzNDWDgKLS0tIHVib0Q2V0Q4dk9yM3JWc21xS3VD
            S1FqbWRyaWVWVEozSDlveGk1ZGg3ZWsKQgUKQaeHIFBQ/JJBsfePdTlRuzwFGuki
            wEqwT0GxE31mguLszx0K0Uh1CGzaGFhEcS3Dyu3DqVm6zoRUe+JVyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-23T08:21:29Z"
    mac: ENC[AES256_GCM,data:LCp1oYXH3EaBoiC6zeHyhQiVE0WMGApBH5lmVggk87HDIs+VMiaILAq6PKqtx+Jv+48LgrrrPw5Own8j7ykvp/JY6Dc0c414waJBT7mBwWvB1b00vyqNHLEFsI2ngJRTlrlmBQB3G+1I68wt9T9YVk1x6DPnG2sewha420LoBIc=,iv:Ck4pwQnpiz/mrnZolzFWcxUo+PXBN65ZmzdHhb2yKfY=,tag:yaCAGxDBt7hR21RQ3Kf8cw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
