apiVersion: v1
stringData:
    age.agekey: null
kind: Secret
metadata:
    name: age-key-secret
    namespace: flux-system
sops:
    age:
        - recipient: age19kyyjnd32na99sn2d4ktqddykrmnghu6tk34fsy9l9duyu2g95ssypk7vy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvOVNZd2Zla2tUa08rM2RU
            cGp1NEJYcXhBVWNnRnZ2V2lxRzcrYTFkWm1RCjlKcDJKVnVBY1l1YU5EQjRBc2tV
            S29qOGZ6N3B4WXVSTEc3alF4cFZWVlEKLS0tIGF2cGFOSXNtWFB6dnI0d2lLMU5u
            Ukpyc2piN1JzaXdDN0N0ZlNEb1RSbTAKgd/3KHZ86DltvT9VtZDTv7lczH4SMU1+
            sHZNwy08a4zp0cMiCZ3wTL8qtZu1sQi9cezkhgE84igwE2Btc5/6RQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-22T14:24:19Z"
    mac: ENC[AES256_GCM,data:fJG6ZAsehh/oS2mXtLAQ67ebihIX12leBBGdsvF0S7L5O611UxVoD6kRZQDhUTyf9eLd27u4RO5de8NWDcntq8r5NxRjpiXmrdA6xBJSkJG6VVDOJIjo9Z0GL/EPViM0PDWbBxEujGZ3+0G3cHWKneW/ys0QOlpV5hBKWDWOaek=,iv:xgLXLXT3YWWWTR/IcqVZ3GXOf1i0qlGEVp9M1Voo8i0=,tag:1c5q/WUtKDdqEc4ZJ2xKyQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
