apiVersion: v1
data:
    identity: null
    identity.pub: null
    known_hosts: null
kind: Secret
metadata:
    name: git-pull-secret
sops:
    age:
        - recipient: age19kyyjnd32na99sn2d4ktqddykrmnghu6tk34fsy9l9duyu2g95ssypk7vy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGNnJGMzJ5ZFF2RmlIaGNF
            N2hzbE5mNmxxV0dWTnl6SEx2S3ZSS2lrMnhrCnNpRGJZKzR0c25wbHZnWS93OVJU
            SG04dHYyR0RvdVFydnk3eFJIaHN5Q2cKLS0tIDZhWVlzc2NNZEhzVDJzcURidXVM
            Q0NYV1RPZFBYcTFxUXhVZ3hGanVEMmMKIgih+PnvuWGbzZKSpCPnKO68cPZccIMp
            PY75EDNLQGy+/Ojucb3ygSCsIg3Ju7RCFnW+swHWSGUucOHfnnbWHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-22T14:24:25Z"
    mac: ENC[AES256_GCM,data:ES55Cr3p9nAgDgTxNClEF9oKxKdoVotyuU884EM9Vs4XkXq9sOpSibRVyQugw+9XxTvuUxi0BC2jZCvhKRfnUXUPEpRrFw900KtWAN8exPcJWP5Ij5r6OwbTzY8Rpg2BtLA4+LBAeN4nRLgWf8EK+7xfl97UKTstrWqgQAjRoNE=,iv:Eh6QDMnWnnY8VpYYgRCuyfcvahDESqqyM8JA1dm2XYM=,tag:FIBJvwg++LHLHLdd+XFBkQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
